# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=20)),
                ('nome_completo', models.CharField(max_length=40)),
                ('menssagem', models.CharField(max_length=500)),
            ],
        ),
    ]
